version: 2

jobs:
    build:
        docker:
            - image: circleci/golang:1.15
        working_directory: /go/src/github.com/jmoney/aws-cost-maintenance
        steps:
            - checkout
            - run: 
                name: build
                command: make build
    release:
        docker:
            - image: circleci/golang:1.15
        working_directory: /go/src/github.com/jmoney/aws-cost-maintenance
        steps:
            - checkout
            - run:
                name: Install tools
                command: curl -sL https://git.io/goreleaser | bash
            - run:
                name: Run goreleaser
                command: goreleaser
workflows:
    version: 2
    build-workflow:
        jobs:
            - build:
                filters:
                    branches:
                        only: /.*/
                    tags:
                        ignore: /.*/
    release-workflow:
        jobs:
          - build:
              filters:
                  branches:
                    ignore: /.*/
                  tags:
                    only: /v(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)?/
          - release:
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*))(?:\.(0|(?:[1-9]\d*)))?(?:\-([\w][\w\.\-_]*))?)?/
