version: 2

jobs:
    build:
        docker:
            - image: circleci/golang:1.14
        working_directory: /go/src/github.com/jmoney8080/aws-cost-maintenance
        steps:
            - checkout
            - run: 
                name: build
                command: make build
workflows:
    version: 2
    commit-workflow:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
